### ISSUE TITLE
Multipart requests

### ISSUE THREAD

**Issue by smskin** [AlexKletn/apiit#1]
**Is your feature request related to a problem? Please describe.**
This library doesn't support the multipart requests

**Describe the solution you'd like**
It is necessary to implement support for multipart requests (for example, to send files)

**Comment by AlexKletn** [comment]
Example of sending a file using `multipart/form-data`:

```ts
host.createEndpoint<{ file: File }, void>('post', '/file-server', {
  dataFormat: 'form-data',
  paramsConfig: {
    file: {
      in: "body"
    }
  }
})
```

I'll add this to the documentation
